### ISSUE TITLE
Compiling / usage on FreeBSD

### ISSUE THREAD

**Issue by dejanstrbac** [slusarz/dovecot-fts-flatcurve#20] opened 2022-02-04 11:43 UTC
Hi

Thank you for your work on this plugin!
I've tried compiling it on FreeBSD but the only way I could get to compile it is by manually changing the config.status after configure to include the headers path:

```
-S["XAPIAN_LIBS"]="-L/usr/local/lib -lxapian"
+S["XAPIAN_LIBS"]="-L/usr/local/lib -lxapian -I/usr/local/include"
```

Once running doveadm index on a never indexed mailbox, FTS gets locked, eventually timing out.

```
Debug: fts-flatcurve(INBOX): Waiting for DB (RW; current.1643974776251308) lock
Debug: fts-flatcurve(INBOX): Waiting for DB (RW; current.1643974776251308) lock
...
Fatal: fts-flatcurve: Could not obtain DB lock (RW; current.1643974776251308)
```

Tried with default settings:

```
  fts = flatcurve
  fts_flatcurve_commit_limit = 500
  fts_flatcurve_max_term_size = 30
  fts_flatcurve_min_term_size = 2
  fts_flatcurve_optimize_limit = 10
  fts_flatcurve_rotate_size = 5000
  fts_flatcurve_rotate_time = 5000
  fts_flatcurve_substring_search = no
  fts_languages = en es de
  fts_tokenizer_generic = algorithm=simple
  fts_tokenizers = generic email-address
```

Any hint is appreciated!

**Comment by Nimloth** [comment] 2022-02-06 19:06
During configure, xapian-config is called to get the path both for the libs (xapian-config --ltlibs) and the headers (xapian-config --cxxflags). They are assigned to the variables XAPIAN_LIBS and XAPIAN_CXXFLAGS respectively.
However, in src/Makefile.in, only XAPIAN_LIBS is used when generating the flags for the compiler.
At a first glance, try replacing
AM_CXXFLAGS = \
        $(XAPIAN_LIBS)
with
AM_CXXFLAGS = \
        $(XAPIAN_LIBS) $(XAPIAN_CXXFLAGS)
in src/Makefile.in

**Comment by Nimloth** [comment] 2022-02-07 08:44
For what it is worth, I have cobbled together a port that compiles (and works) for me:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261766
Feel free to try - feedback is very welcome.

**Comment by slusarz** [comment] 2022-02-07 22:28
I merged #21 which should fix the compiler errors.

As for the runtime error - @Nimloth mentions that he can get this running just fine on BSD (I don't have a BSD test machine).  Unless a reproducible test case can be generated, I'm not sure there's much more I can do since the code does seems to work in at least some usages.

**Comment by slusarz** [comment] 2022-02-07 22:29
Are you using NFS?

**Comment by dejanstrbac** [comment] 2022-02-07 22:54
Yes, tried it on NFS mounted mails storage. Is there a known limitation with NFS?

**Comment by slusarz** [comment] 2022-03-30 22:07
The new file locking solution has been backported from 2.4 core.  Can you try the new code and see if it improves things?

**Comment by slusarz** [comment] 2022-04-29 18:51
Closing, as this was confirmed fixed on at least one BSD test machine.

**Closed by slusarz** 2022-04-29 18:51 UTC
