### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by kour1er** [slusarz/dovecot-fts-flatcurve#18] opened 2021-12-21 16:41 UTC
I don't know whether this is in scope of your project but I would love to have fts-flatcurve running on macOS. I've got it to compile, but when I run Dovecot with it and run a search I get:

`Dec 21 14:56:46 indexer-worker(pid 20949 user kour1er): Fatal: master: service(indexer-worker): child 20949 killed with signal 11 (core dumps disabled - https://dovecot.org/bugreport.html#coredumps)`

This is the latest git version running against Dovecot 2.3.17.1 on Intel. I've attached the indexer-worker crash log in case that of any use.
[indexer-worker.txt](https://github.com/slusarz/dovecot-fts-flatcurve/files/7756521/indexer-worker.txt)

**Comment by slusarz** [comment] 2021-12-23 04:54
At the present time, I can't support MacOS because I don't have access to a system.  Generally, Dovecot should work with it, although there are a few things (e.g. local resource polling) that don't play super well.

All that being said, I don't think flatcurve is using anything too crazy.  If Xapian works on MacOS (I have no idea if it does or not), we should be ok.

Looking at your crash log - it's a bit strange because the stack trace isn't accurate.  The last 2 stack items are      "fts_flatcurve_xapian_write_db_get" and "fts_flatcurve_xapian_init_msg", but the former isn't called in the latter, so there are function calls missing in between at a minimum.  (Or, MacOS just does crash logs in a way that I don't understand.)

At this point, I would really need either a way of reproducing on a system that I can debug on, or else I would need someone to do full debug and provide the root cause of the crash.  It will be difficult to analyze further without one of those two.

I'll note that it's not crashing trying to do the search - it's crashing while indexing messages.  So this doesn't seem to have anything to do with the actual searching, it has to do with parsing messages in the mailbox to build the search DB.  You can try using the "doveadm fts-flatcurve" commands to see if anything is being built - that might narrow down the issue.  If a specific message is causing the crash, that might be interesting and reproducible.  If you are unable to index any message (i.e. it crashes as soon as indexing begins), that might lean towards something specific to the environment instead.

**Comment by kour1er** [comment] 2021-12-24 11:48
Totally fair enough!

Just as a point of reference, Xapian does work on macOS - it's in both Brew and MacPorts (the two main package management systems).

I will certainly try your suggestions and report back if there is anything useful. Thanks very much for your detailed response - much appreciated.

**Comment by slusarz** [comment] 2021-12-30 06:18
Closing (for now), as I am unable to debug further myself.

**Closed by slusarz** 2021-12-30 06:18 UTC

**Comment by sthen** [comment] 2022-01-04 14:29
Given the backtrace, I think there's a fair chance this is the same problem I'm hitting in #16
