### ISSUE TITLE
Filename too long errors during FTS optimize

### ISSUE THREAD

**Issue by mstilkerich** [slusarz/dovecot-fts-flatcurve#40] opened 2022-12-22 08:02 UTC
Hello,

  I recently switched to this FTS plugin. I am running a nightly cronjob doing `doveadm fts optimize -A`.

For one user, I get "filename too long" errors during this indexing, where the error message shows a path that appears to be a concatenation of all paths of the user's mailboxes.

The message looks like this:
```
doveadm(mailuser): Error: fts-flatcurve: stat(/srv/dovecot/mails/mailuser/mailboxes/BOX1/dbox-Mails/fts-flatcurve//srv/dovecot/mails/mailuser/mailboxes/BOX2/dbox-Mails/fts-flatcurve//srv/dovecot/mails/mailuser/mailboxes/BOX3/dbox-Mails/fts-flatcurve/) failed: File name too long
```

I have shortened this example message to 3 mailboxes, the actual message contains 57 mailboxes and the resulting path in the error message has a length of 4136 characters. However, since this concatenation is not a valid path and a stat is attempted on it, I suspect this to be an issue in the plugin?

I get 28 of these messages during the doveadm execution, but all appear identical (same user, same path). The user has a total of 76 mailboxes.

If there is any helpful information I can provide for this, please let me know.

I am using dovecot 2.3.19.1 with fts-flatcurve 0.3.3. Just moved to 2.3.20 but issue remains.

**Comment by mstilkerich** [comment] 2022-12-26 18:57
The issue just vanished after I opened this issue, before I got it several nights during the nightly optimize run. Maybe the 2.3.20 upgrade and the initial fts optimize afterwards where I still got the errors did fix them?! Anyway, for me this issue is resolved.

**Comment by mstilkerich** [comment] 2023-03-22 04:33
Since a while, I‘ve been getting these errors again for my nightly fts optimize, also for other users.

**Comment by slusarz** [comment] 2023-04-05 05:40
Would be useful if you could add debug logging for flatcurve and post full logs for the broken accounts.

At least:
`log_debug = event=fts_flatcurve_optimize`

And/or running doveadm with the `-D` option as well.

**Comment by slusarz** [comment] 2023-04-06 00:37
See above commit - I can't reproduce this behavior in CI testing with a fairly simple setup.

**Comment by slusarz** [comment] 2023-05-16 18:39
No feedback.  Closing.

**Closed by slusarz** 2023-05-16 18:39 UTC
