### ISSUE TITLE
Email tokenizer is triggered by not-email tokens, fx. a link including an email parameter

### ISSUE THREAD

**Issue by danieldemus** [slusarz/dovecot-fts-flatcurve#69] opened 2024-08-25 22:52 UTC
Fx. `bytes=209715200#011userdb_password={crypt}$6$j9z0n7soq1edwirw$9h3chtthiat5.s0pwfjo/zqq74f.5hd0puiv3bpooiams75ykatfji7kgt2xvutol/pprmguapdxialyekrs.0#011userdb_home=/home/webserver/mail/ourdomian1.com/email#011uid=502#011userdb_user=email@ourdomian1.c`

results in 'Could not write message data: uid=8272; InvalidArgumentError: Term too long (> 245)' being logged.
I gather from other recent issues that it's the email tokenizer that complains, but it should not be tokenizing the entire URI or in reality any URI.

**Comment by slusarz** [comment] 2024-08-26 02:32
Duplicate of #62 (specifically, preventing "Term too long" errors).  Specifically, see https://github.com/slusarz/dovecot-fts-flatcurve/issues/62#issuecomment-2287576540

flatcurve has nothing to do with tokenization semantics - tokenization is done by Dovecot core code.  So any improvements to tokenization must be discussed there.

**Closed by slusarz** 2024-08-26 02:32 UTC
